version: "3.8"

services:
  dev-db:
    image: postgres:15-alpine
    container_name: recruitment-dev-db
    restart: unless-stopped
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: recruitment_user
      POSTGRES_PASSWORD: recruitment123
      POSTGRES_DB: recruitment_db
    volumes:
      - recruitment-dev-data:/var/lib/postgresql/data
    networks:
      - recruitment-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U recruitment_user -d recruitment_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  test-db:
    image: postgres:15-alpine
    container_name: recruitment-test-db
    restart: unless-stopped
    ports:
      - "5437:5432"
    environment:
      POSTGRES_USER: recruitment_user
      POSTGRES_PASSWORD: recruitment123
      POSTGRES_DB: recruitment_test_db
    volumes:
      - recruitment-test-data:/var/lib/postgresql/data
    networks:
      - recruitment-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U recruitment_user -d recruitment_test_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  recruitment-dev-data:
    name: recruitment-dev-data
  recruitment-test-data:
    name: recruitment-test-data

networks:
  recruitment-network:
    name: recruitment-network
    driver: bridge
